# AutoDoor OCR 识别系统 - Gitee 流水线配置
# 使用 Gitee 流水线 v1.0 语法

version: '1.0'
name: autodoor-build
name-cn: AutoDoor
displayName: AutoDoor
description: 自动构建 Windows 和 macOS 版本的 AutoDoor 程序

stages:
  - stage:
    name: build_windows
    name-cn: Windows 构建
    displayName: Windows 构建
    steps:
      - step: run@command
        name: build_windows
        displayName: 构建 Windows 版本
        runInContainer: false
        shell: cmd
        commands:
          - echo 开始构建 Windows 版本...
          - python --version
          - pip --version
          - pip install -r requirements.txt pyinstaller
          - pyinstaller autodoor.spec --noconfirm
          - echo Windows 版本构建完成
        artifacts:
          - name: autodoor-windows
            path: dist/autodoor/
            expireIn: 30d

  - stage:
    name: build_macos
    name-cn: macOS 构建
    displayName: macOS 构建
    steps:
      - step: run@command
        name: build_macos
        displayName: 构建 macOS 版本
        runInContainer: false
        shell: bash
        commands:
          - echo 开始构建 macOS 版本...
          - python3 --version
          - pip3 --version
          - pip3 install -r requirements.txt pyinstaller
          - pyinstaller autodoor.spec --noconfirm
          - echo macOS 版本构建完成
        artifacts:
          - name: autodoor-macos
            path: dist/autodoor/
            expireIn: 30d

triggers:
  push:
    branches:
      include:
        - master
  manual:
    enabled: true
